name: Extract Token
on:
  workflow_dispatch:
jobs:
  extract:
    runs-on: ubuntu-latest
    steps:
      - name: Write tokens
        run: |
          echo "${{ secrets.INSTAGRAM_ACCESS_TOKEN }}" > token.txt
          echo "${{ secrets.INSTAGRAM_USER_ID }}" >> token.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ig-tokens
          path: token.txt
